# Generated by Django 4.2.2 on 2023-07-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessment_course_question_option_coursecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='Course',
            new_name='course',
        ),
    ]
