# Generated by Django 4.2.2 on 2023-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_course_coursecontent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='url',
            field=models.URLField(default='https://youtu.be/WvA699KXucE', max_length=250),
            preserve_default=False,
        ),
    ]
