# Generated by Django 4.2.2 on 2023-07-07 18:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursecontent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='url',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='content_video',
            field=embed_video.fields.EmbedVideoField(default='https://youtu.be/WvA699KXucE'),
            preserve_default=False,
        ),
    ]
